### ISSUE TITLE
Add Authors 

### ISSUE THREAD

**Issue by dridk** [labsquare/Poster#2]
@labsquare/developers 
S. Schutz, P. Marijon, E. Trounev,  J.  Roquet, F. Pina-Martins, N.
Lavielle, J. Sallou , O. Gueudelot, AS. Denommé

You may want to add a footer or something else to display information ?

**Comment by StuntsPT** [comment]
If you are adding affiliations, here are mine:

1.    Departamento de Biologia Animal, Faculdade de Ciências, Computational Biology and Population Genomics Group, cE3c - Centre for Ecology, Evolution and Environmental Changes, Universidade de Lisboa, Campo Grande
2.    Departamento de Biologia e CESAM, Univ. de Aveiro

Thanks!

**Comment by it-s** [comment]
Ok this is now done
