### ISSUE TITLE
Add some logo

### ISSUE THREAD

**Issue by dridk** [labsquare/Poster#3]
You should add some logo ?

# Qt logo ( svg avaible)
You have here several official Qt logo " Made with logo "
http://blog.qt.io/blog/2016/06/20/introducing-new-built-with-qt-logo/

![image](https://user-images.githubusercontent.com/1911063/27259520-55709af2-5415-11e7-9097-89b6a9445882.png)

# GPL3 Logo  (svg avaible)
![image](https://user-images.githubusercontent.com/1911063/27259538-8770ecaa-5415-11e7-8788-87c1ef9b2c21.png)

# Global alliance for genomics ( looking for svg)
![image](https://user-images.githubusercontent.com/1911063/27259559-d1dd4d1a-5415-11e7-94dc-21bcc01c56ad.png)

**Comment by it-s** [comment]
Added all logos the the bottom of the poster
