### ISSUE TITLE
binary code to ACGT code ? 

### ISSUE THREAD

**Issue by dridk** [labsquare/Poster#5]
What if you replace 0101 code from the center by ACGT code ? 
And by using color instead yellow ? Somthing close to : 

![image](https://user-images.githubusercontent.com/1911063/27259594-ad81119e-5416-11e7-9dd9-e22c7bae386c.png)

**Comment by it-s** [comment]
can you give me some real code sequence? the longer the better. Something cool too. So at the fair you could talk about it too.

**Comment by dridk** [comment]
Oh... good idea...  I can encode some secret message !

**Comment by dridk** [comment]
http://earthsciweb.org/js/bio/dna-writer/

Is it enough?
This is a piece of text from my favourite book.

TAGCGTCTAGACAGCCGTACTGTACTAAGCTCATGTACACTAAGCACTAGCATCTGTCTCGTCAGCATGACTGACAGCTAGCGTTGTTGACTAAGCCACCTAGAGATCCTGTCAACTTAGTGTCACTGAACGAGCCTCTGTATGAGCTAGCGTCTAGACAGCGTCTGTAGCCATGACAGCTAGCGTCTAAGCCTCACTACACTAAGCAGCTGTGCTAGCGTCCTACTCCTATGAAGCACTCTCTACAGCATGCTAAGCACTCACCTAAGCTAGCGTCTACTGCACAGCTGAGATCACGTACTGGTAACTATCAGCACAACTTCACGTCTGCTCCTATGAACGAGC

**Comment by it-s** [comment]
Relaced
