### ISSUE TITLE
Application Screenshot

### ISSUE THREAD

**Issue by dridk** [labsquare/Poster#6]
# FastQt 
Fastq file analyser 
https://github.com/labsquare/fastQt
[[ SVG SCREENSHOT ]](https://framadrop.org/r/ze2wduHc-Q#tJoH0zc/eAlav9vY3qGYBD/rcBzT5miNchv1379D9yE=)

# CutePeaks
Sanger Trace file viewer 
https://github.com/labsquare/CutePeaks
[[ SVG SCREENSHOT ]](https://framadrop.org/r/90x_h2WlyF#D0y993jQrbsFI4rgldOw07a5uwnpJTOD5DwnqHoat4U=)

# CuteVCF 
VCF viewer 
https://github.com/labsquare/CuteVCF
[[ SVG SCREENSHOT ]](https://framadrop.org/r/O_ma-wksr1#oD88pSeY9sQZSGjZ1fJt/Qd3R+XF4zEowjm6XzQIOMo=)

# BigBrowser ( not finished)
Cannot convert the chromosom to svg.. 
So you can avoid it

**Comment by it-s** [comment]
Updated the screenshots
