### ISSUE TITLE
Highlight title ? 

### ISSUE THREAD

**Issue by dridk** [labsquare/Poster#8]
Not easy to make the difference between text and title

![image](https://user-images.githubusercontent.com/1911063/27261359-c609f8d6-5441-11e7-827f-a2652518b872.png)

**Comment by dridk** [comment]
And maybe Qt logo  and github logo ? 
![image](https://user-images.githubusercontent.com/1911063/27261388-79386168-5442-11e7-8c83-0efdd0a1875c.png)

**Comment by it-s** [comment]
Titles are now highlighted
